### ISSUE TITLE
power-assert is not working now

### ISSUE THREAD

**Issue by kjirou** [kjirou/_hakusura#6]
T/O

**Comment by twada** [comment]
What's happend?

**Comment by kjirou** [comment]
@twada Hello! thank you for your comment.

I have summarized the situation in the above pull-req.
Could you check it?

In addition, it has been resolved for me, because there is no problem unless I use the `zero-config mode`.

**Comment by twada** [comment]
Thank you for your reporting and PR. It saved time a lot.
I'm digging this issue in, nothing is solved though.
Hmm, so wired...

**Comment by twada** [comment]
I found a hint here.
Maybe there is a conflict between `babel/register` and `espower-babel` ?

When I delete `require('babel/register');` from `env/test.js`, 
`$(npm bin)/mocha --compilers js:espower-babel/guess test/vendors/power-assert.js` works as expected.
But `npm run` does not.

**Comment by kjirou** [comment]
I have summarized verification results again to https://github.com/kjirou/reproduce-power-assert-bug/issues/1 .
But, unfortunately, this is my best..

May the force be with you!
